/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as JoinReviewRouteImport } from './routes/join/review'
import { Route as JoinConversationRouteImport } from './routes/join/conversation'
import { Route as ExampleStoreRouteImport } from './routes/example/store'
import { Route as ExampleRestApiRouteImport } from './routes/example/rest-api'
import { Route as ExampleChatRouteImport } from './routes/example/chat'
import { Route as AdminPipelineRouteImport } from './routes/admin/pipeline'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ExamplePostsIndexRouteImport } from './routes/example/posts/index'
import { Route as ExamplePostsPostIdRouteImport } from './routes/example/posts/$postId'
import { Route as ExampleApiChatRouteImport } from './routes/example/api.chat'
import { Route as AdminCandidatesIdRouteImport } from './routes/admin/candidates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinReviewRoute = JoinReviewRouteImport.update({
  id: '/join/review',
  path: '/join/review',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinConversationRoute = JoinConversationRouteImport.update({
  id: '/join/conversation',
  path: '/join/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleStoreRoute = ExampleStoreRouteImport.update({
  id: '/example/store',
  path: '/example/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRestApiRoute = ExampleRestApiRouteImport.update({
  id: '/example/rest-api',
  path: '/example/rest-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleChatRoute = ExampleChatRouteImport.update({
  id: '/example/chat',
  path: '/example/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplePostsIndexRoute = ExamplePostsIndexRouteImport.update({
  id: '/example/posts/',
  path: '/example/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplePostsPostIdRoute = ExamplePostsPostIdRouteImport.update({
  id: '/example/posts/$postId',
  path: '/example/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleApiChatRoute = ExampleApiChatRouteImport.update({
  id: '/example/api/chat',
  path: '/example/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesIdRoute = AdminCandidatesIdRouteImport.update({
  id: '/admin/candidates/$id',
  path: '/admin/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/example/chat': typeof ExampleChatRoute
  '/example/rest-api': typeof ExampleRestApiRoute
  '/example/store': typeof ExampleStoreRoute
  '/join/conversation': typeof JoinConversationRoute
  '/join/review': typeof JoinReviewRoute
  '/admin': typeof AdminIndexRoute
  '/join': typeof JoinIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof ExamplePostsPostIdRoute
  '/example/posts': typeof ExamplePostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/example/chat': typeof ExampleChatRoute
  '/example/rest-api': typeof ExampleRestApiRoute
  '/example/store': typeof ExampleStoreRoute
  '/join/conversation': typeof JoinConversationRoute
  '/join/review': typeof JoinReviewRoute
  '/admin': typeof AdminIndexRoute
  '/join': typeof JoinIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof ExamplePostsPostIdRoute
  '/example/posts': typeof ExamplePostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/example/chat': typeof ExampleChatRoute
  '/example/rest-api': typeof ExampleRestApiRoute
  '/example/store': typeof ExampleStoreRoute
  '/join/conversation': typeof JoinConversationRoute
  '/join/review': typeof JoinReviewRoute
  '/admin/': typeof AdminIndexRoute
  '/join/': typeof JoinIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof ExamplePostsPostIdRoute
  '/example/posts/': typeof ExamplePostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/pipeline'
    | '/example/chat'
    | '/example/rest-api'
    | '/example/store'
    | '/join/conversation'
    | '/join/review'
    | '/admin'
    | '/join'
    | '/admin/candidates/$id'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/pipeline'
    | '/example/chat'
    | '/example/rest-api'
    | '/example/store'
    | '/join/conversation'
    | '/join/review'
    | '/admin'
    | '/join'
    | '/admin/candidates/$id'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/pipeline'
    | '/example/chat'
    | '/example/rest-api'
    | '/example/store'
    | '/join/conversation'
    | '/join/review'
    | '/admin/'
    | '/join/'
    | '/admin/candidates/$id'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  ExampleChatRoute: typeof ExampleChatRoute
  ExampleRestApiRoute: typeof ExampleRestApiRoute
  ExampleStoreRoute: typeof ExampleStoreRoute
  JoinConversationRoute: typeof JoinConversationRoute
  JoinReviewRoute: typeof JoinReviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JoinIndexRoute: typeof JoinIndexRoute
  AdminCandidatesIdRoute: typeof AdminCandidatesIdRoute
  ExampleApiChatRoute: typeof ExampleApiChatRoute
  ExamplePostsPostIdRoute: typeof ExamplePostsPostIdRoute
  ExamplePostsIndexRoute: typeof ExamplePostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/review': {
      id: '/join/review'
      path: '/join/review'
      fullPath: '/join/review'
      preLoaderRoute: typeof JoinReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/conversation': {
      id: '/join/conversation'
      path: '/join/conversation'
      fullPath: '/join/conversation'
      preLoaderRoute: typeof JoinConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/store': {
      id: '/example/store'
      path: '/example/store'
      fullPath: '/example/store'
      preLoaderRoute: typeof ExampleStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/rest-api': {
      id: '/example/rest-api'
      path: '/example/rest-api'
      fullPath: '/example/rest-api'
      preLoaderRoute: typeof ExampleRestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/chat': {
      id: '/example/chat'
      path: '/example/chat'
      fullPath: '/example/chat'
      preLoaderRoute: typeof ExampleChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/posts/': {
      id: '/example/posts/'
      path: '/example/posts'
      fullPath: '/example/posts'
      preLoaderRoute: typeof ExamplePostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/posts/$postId': {
      id: '/example/posts/$postId'
      path: '/example/posts/$postId'
      fullPath: '/example/posts/$postId'
      preLoaderRoute: typeof ExamplePostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/api/chat': {
      id: '/example/api/chat'
      path: '/example/api/chat'
      fullPath: '/example/api/chat'
      preLoaderRoute: typeof ExampleApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates/$id': {
      id: '/admin/candidates/$id'
      path: '/admin/candidates/$id'
      fullPath: '/admin/candidates/$id'
      preLoaderRoute: typeof AdminCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  ExampleChatRoute: ExampleChatRoute,
  ExampleRestApiRoute: ExampleRestApiRoute,
  ExampleStoreRoute: ExampleStoreRoute,
  JoinConversationRoute: JoinConversationRoute,
  JoinReviewRoute: JoinReviewRoute,
  AdminIndexRoute: AdminIndexRoute,
  JoinIndexRoute: JoinIndexRoute,
  AdminCandidatesIdRoute: AdminCandidatesIdRoute,
  ExampleApiChatRoute: ExampleApiChatRoute,
  ExamplePostsPostIdRoute: ExamplePostsPostIdRoute,
  ExamplePostsIndexRoute: ExamplePostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
